omron:
  pointcloud_to_laserscan:
    ros__parameters:
      target_frame: omron/base_footprint
      transform_tolerance: 0.01
      min_height: -1.0
      max_height: 2.0
      angle_min: -3.0  # -M_PI/2
      angle_max: 0.8  # M_PI/2
      angle_increment: 0.00087  # M_PI/360.0
      scan_time: 0.3333
      range_min: 0.1
      range_max: 20.0
      use_inf: True
      inf_epsilon: 1.0